The solution has been created
MikutishviliDavid/LabelPlace pull request #1
Opened 2022-08-10 10:11 UTC by MikutishviliDavid

2022-08-10 10:50 UTC, SiarheiHasiuk commented
In your entities you can move "Id" to separate entity and just inherit this entity.

2022-08-18 10:04 UTC, DzmitryBratchuk requested changes

2022-08-18 10:04 UTC, DzmitryBratchuk commented on LabelPlace.DAL/DataContext.cs
> +namespace LabelPlace.DAL
LabelPlace.Dal or LabelPlace.DataAccess

2022-08-18 10:04 UTC, DzmitryBratchuk commented on LabelPlace.DAL/DataContext.cs
> +    public class DataContext : DbContext
Bad context name. Imagine that this application needed a second context. Would the name be DataContext2?

2022-08-18 10:04 UTC, DzmitryBratchuk commented on LabelPlace.DAL/DataContext.cs
> +            Database.EnsureCreated();
You shouldn't use Database.EnsureCreated() here.
Please read https://docs.microsoft.com/en-us/ef/core/managing-schemas/ensure-created

2022-08-18 10:04 UTC, DzmitryBratchuk commented on LabelPlace.DAL/DataContext.cs
> +            modelBuilder.ApplyConfiguration(new UserConfiguration());
You can use just one call: ApplyConfigurationsFromAssembly

2022-08-18 10:04 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Entities/User.cs
> +        public ICollection<Role> Roles { get; set; }
Please initialize collections ... = new HashSet<...>();

2022-08-18 10:04 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Entities/Project.cs
> +        public ProjectType Type { get; set; }
Please sort logically properties. Ex: strings -> enums -> navigation properties

2022-08-18 10:04 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Enums/ProjectStatus.cs
> +        Paused
Please add a value to indicate that the status is undefined.
Also assign values to each member, because the new values could potentially affect the data in the database

2022-08-18 10:04 UTC, DzmitryBratchuk commented on LabelPlace.Domain/LabelPlace.Domain.csproj
> +    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.10" />
Do you really need this PackageReference in Domain.csproj?

2022-08-18 10:04 UTC, DzmitryBratchuk commented on LabelPlace.Api/Migrations/20220816135631_InitialCreate.Designer.cs
> +namespace LabelPlace.Api.Migrations
Bad place to store Migrations. This folder should be in same project as db Context

2022-08-18 10:04 UTC, DzmitryBratchuk commented on LabelPlace.Api/Migrations/20220816135631_InitialCreate.Designer.cs
> +namespace LabelPlace.Api.Migrations
It is also good practice to create the Initial migration when the development team is fully confident that there will be no changes to the tables and their configurations at this point. So it should be done at least after the code review, not before

2022-08-18 10:04 UTC, DzmitryBratchuk commented on LabelPlace.Api/Properties/launchSettings.json
> +      "launchUrl": "swagger",
This file only for development purposes. 
Do not set swagger setting here. Or you want to use swagger only in development mode? If so, why?
![image](https://user-images.githubusercontent.com/56396360/185365108-e8c22346-6602-47c6-b17c-de23bbffb868.png)

2022-08-18 10:04 UTC, DzmitryBratchuk commented on LabelPlace.Api/Startup.cs
> +            string connection = Configuration.GetConnectionString("DefaultConnection");
Please create model for db configuration, update appsettings.json and call Configuration.GetSection(..)

2022-08-18 10:04 UTC, DzmitryBratchuk commented on LabelPlace.DAL/Configurations/ProjectConfiguration.cs
> +                .WithOne(t => t.Project);
Please add to entities additional appropriate configurations. 
E.g.: IsRequired; IsUnique; HasIndex; maybe string length restrictions (HasMaxLength); also you have some table columns containing json data (this one also configurable).

2022-08-22 16:39 UTC, MikutishviliDavid commented on LabelPlace.DAL/DataContext.cs
> +namespace LabelPlace.DAL
done

2022-08-22 16:39 UTC, MikutishviliDavid commented on LabelPlace.DAL/DataContext.cs
> +    public class DataContext : DbContext
Changed name

2022-08-22 16:39 UTC, MikutishviliDavid commented on LabelPlace.DAL/DataContext.cs
> +            Database.EnsureCreated();
done

2022-08-22 16:40 UTC, MikutishviliDavid commented on LabelPlace.DAL/DataContext.cs
> +            modelBuilder.ApplyConfiguration(new UserConfiguration());
applied it

2022-08-22 16:40 UTC, MikutishviliDavid commented on LabelPlace.Domain/Entities/User.cs
> +        public ICollection<Role> Roles { get; set; }
done

2022-08-22 16:40 UTC, MikutishviliDavid commented on LabelPlace.Domain/Entities/Project.cs
> +        public ProjectType Type { get; set; }
done

2022-08-22 16:41 UTC, MikutishviliDavid commented on LabelPlace.Domain/Enums/ProjectStatus.cs
> +        Paused
done

2022-08-22 16:41 UTC, MikutishviliDavid commented on LabelPlace.Domain/LabelPlace.Domain.csproj
> +    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.10" />
This PackageReference don't need

2022-08-22 16:42 UTC, MikutishviliDavid commented on LabelPlace.Api/Migrations/20220816135631_InitialCreate.Designer.cs
> +namespace LabelPlace.Api.Migrations
okay

2022-08-22 16:42 UTC, MikutishviliDavid commented on LabelPlace.Api/Properties/launchSettings.json
> +      "launchUrl": "swagger",
done

2022-08-22 16:42 UTC, MikutishviliDavid commented on LabelPlace.Api/Startup.cs
> +            string connection = Configuration.GetConnectionString("DefaultConnection");
done

2022-08-22 16:42 UTC, MikutishviliDavid commented on LabelPlace.DAL/Configurations/ProjectConfiguration.cs
> +                .WithOne(t => t.Project);
done

2022-08-23 13:20 UTC, DzmitryBratchuk requested changes

2022-08-23 13:20 UTC, DzmitryBratchuk commented on LabelPlace.Api/appsettings.json
> +  },
Bad naming!
ConnectionStrings -> ConnectionString???

2022-08-23 13:20 UTC, DzmitryBratchuk commented on LabelPlace.DAL/LabelPlace.DAL.csproj
> +</Project>
Now you have 2 projects.  
LabelPlace.DAL and LabelPlace.Dal
Why?

2022-08-23 13:20 UTC, DzmitryBratchuk commented on LabelPlace.DAL/Configurations/CompanyConfiguration.cs
> +            builder.HasKey(k => k.Id);
Should be first config call in this method. You have to sort the calls by importance. Primary Key - the most important

2022-08-23 13:20 UTC, DzmitryBratchuk commented on LabelPlace.DAL/Configurations/CompanyConfiguration.cs
> +                .HasMaxLength(50)
Why 50?

2022-08-23 13:20 UTC, DzmitryBratchuk commented on LabelPlace.DAL/Configurations/CompanyConfiguration.cs
> +                .HasMaxLength(60)
Why 60?

2022-08-24 14:13 UTC, MikutishviliDavid commented on LabelPlace.Api/appsettings.json
> +  },
done

2022-08-24 14:18 UTC, MikutishviliDavid commented on LabelPlace.DAL/Configurations/CompanyConfiguration.cs
> +            builder.HasKey(k => k.Id);
done

2022-08-24 14:19 UTC, MikutishviliDavid commented on LabelPlace.DAL/LabelPlace.DAL.csproj
> +</Project>
I fixed it

2022-08-24 14:20 UTC, MikutishviliDavid commented on LabelPlace.DAL/Configurations/CompanyConfiguration.cs
> +                .HasMaxLength(50)
Fixed

2022-08-24 14:20 UTC, MikutishviliDavid commented on LabelPlace.DAL/Configurations/CompanyConfiguration.cs
> +                .HasMaxLength(60)
Fixed

2022-09-01 13:37 UTC, DzmitryBratchuk requested changes

2022-09-01 13:37 UTC, DzmitryBratchuk commented on LabelPlace.Dal/Configurations/ProjectConfiguration.cs
> +            builder.HasIndex(i => i.Status).IsUnique();
Why Status must be Unique?

2022-09-01 13:37 UTC, DzmitryBratchuk commented on LabelPlace.Dal/Configurations/RoleConfiguration.cs
> +            builder.Property(p => p.Type).IsRequired();
Can be Unique

2022-09-01 13:37 UTC, DzmitryBratchuk commented on LabelPlace.Dal/Configurations/TextAnnotationConfiguration.cs
> +                .IsRequired();
Why IsRequired?

2022-09-01 13:37 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Entities/TextAnnotation.cs
> +        [Column(TypeName = "json")]
Why this is here? ([Column(TypeName = "json")])

2022-09-01 13:37 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Enums/ProjectStatus.cs
> +
Remove empty rows between values

2022-09-01 13:37 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Enums/ProjectType.cs
> +        Text = 0,
Where is default value?

2022-09-01 13:37 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Enums/RoleType.cs
> +        Adminsitrator = 0,
Where is default value?

2022-09-01 13:37 UTC, DzmitryBratchuk commented on LabelPlace.Domain/LabelPlace.Domain.csproj
> +    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
Do you really need all of this packages in Domain project?

2022-09-01 13:37 UTC, DzmitryBratchuk commented on LabelPlace.Dal/LabelPlace.Dal.csproj
> +    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
Do you really need all of this packages in Dal project?

2022-09-01 13:37 UTC, DzmitryBratchuk commented on LabelPlace.Dal/Configurations/UserConfiguration.cs
> +            builder.Property(p => p.Email)
Email must be unique

2022-09-01 13:37 UTC, DzmitryBratchuk commented on LabelPlace.Dal/Configurations/UserConfiguration.cs
> +            builder.Property(p => p.Name)
Why Name and not FirstName and LastName?

2022-09-01 13:37 UTC, DzmitryBratchuk commented on LabelPlace.Dal/LabelPlaceContext.cs
> +        }
Why we need this constructor?

2022-09-01 13:37 UTC, DzmitryBratchuk commented on LabelPlace.Dal/GenericRepository/IGenericRepository.cs
> +            string includeProperties = "");
What is it?

2022-09-01 13:37 UTC, DzmitryBratchuk commented on LabelPlace.Dal/GenericRepository/IGenericRepository.cs
> +        TEntity GetById(object id);
I think this can be removed cause we have different Id types

2022-09-02 09:57 UTC, MikutishviliDavid commented on LabelPlace.Dal/Configurations/ProjectConfiguration.cs
> +            builder.HasIndex(i => i.Status).IsUnique();
I deleted status IsUnique

2022-09-02 10:01 UTC, MikutishviliDavid commented on LabelPlace.Dal/Configurations/RoleConfiguration.cs
> +            builder.Property(p => p.Type).IsRequired();
I made it Unique

2022-09-02 11:24 UTC, MikutishviliDavid commented on LabelPlace.Dal/Configurations/UserConfiguration.cs
> +            builder.Property(p => p.Email)
done

2022-09-02 11:26 UTC, MikutishviliDavid commented on LabelPlace.Domain/Enums/ProjectStatus.cs
> +
done

2022-09-02 11:50 UTC, MikutishviliDavid commented on LabelPlace.Dal/Configurations/TextAnnotationConfiguration.cs
> +                .IsRequired();
Fixed it

2022-09-02 11:51 UTC, MikutishviliDavid commented on LabelPlace.Domain/Entities/TextAnnotation.cs
> +        [Column(TypeName = "json")]
I forgot to delete it

2022-09-02 11:53 UTC, MikutishviliDavid commented on LabelPlace.Domain/Enums/ProjectType.cs
> +        Text = 0,
Added

2022-09-02 11:53 UTC, MikutishviliDavid commented on LabelPlace.Domain/Enums/RoleType.cs
> +        Adminsitrator = 0,
Added

2022-09-02 12:06 UTC, MikutishviliDavid commented on LabelPlace.Domain/LabelPlace.Domain.csproj
> +    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
It doesn't need all the packages

2022-09-02 12:23 UTC, MikutishviliDavid commented on LabelPlace.Dal/LabelPlace.Dal.csproj
> +    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
I left only Npgsql.EntityFrameworkCore.PostgreSQL

2022-09-02 12:27 UTC, MikutishviliDavid commented on LabelPlace.Dal/Configurations/UserConfiguration.cs
> +            builder.Property(p => p.Name)
I corrected it

2022-09-02 12:36 UTC, MikutishviliDavid commented on LabelPlace.Dal/LabelPlaceContext.cs
> +        }
I can't use UnitOfWork without this constructor

2022-09-02 12:44 UTC, MikutishviliDavid commented on LabelPlace.Dal/GenericRepository/IGenericRepository.cs
> +            string includeProperties = "");
I changed the implementation

2022-09-02 12:45 UTC, MikutishviliDavid commented on LabelPlace.Dal/GenericRepository/IGenericRepository.cs
> +        TEntity GetById(object id);
done

2022-09-07 09:25 UTC, DzmitryBratchuk commented on LabelPlace.Dal/LabelPlace.Dal.csproj
> +    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
Why?

> I left only Npgsql.EntityFrameworkCore.PostgreSQL

2022-09-07 09:46 UTC, DzmitryBratchuk commented on LabelPlace.Dal/LabelPlaceContext.cs
> +        }
I'm sure you can!

2022-09-08 16:15 UTC, DzmitryBratchuk requested changes

2022-09-08 16:15 UTC, DzmitryBratchuk commented on LabelPlace.Dal/GenericRepository/GenericRepository.cs
> +            TEntity entityToDelete = _entities.Find(id);
Entity search must be outside this method

2022-09-08 16:15 UTC, DzmitryBratchuk commented on LabelPlace.Dal/GenericRepository/GenericRepository.cs
> +        public virtual void Delete(TEntity entityToDelete)
You have 2 virtual Delete methods, but Interface has one.
What do you think we should do? If you consider the comment above

2022-09-08 16:15 UTC, DzmitryBratchuk commented on LabelPlace.Dal/GenericRepository/IGenericRepository.cs
> +    public interface IGenericRepository<TEntity> where TEntity : class
IBaseRepository name will be better.

Also think about how you can try to solve this problem.
![image](https://user-images.githubusercontent.com/56396360/189163590-af5de8a5-c3f9-4f23-b035-639954ff7f57.png)

2022-09-08 16:15 UTC, DzmitryBratchuk commented on LabelPlace.Dal/LabelPlaceContext.cs
> +            modelBuilder.ApplyConfigurationsFromAssembly(typeof(CompanyConfiguration).Assembly);
You can use Assembly.GetExecutingAssembly() to get the currently executing assembly
[Assembly.GetExecutingAssembly](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getexecutingassembly)

2022-09-08 16:15 UTC, DzmitryBratchuk commented on LabelPlace.Dal/GenericRepository/GenericRepository.cs
> +        private readonly DbSet<TEntity> _entities;
I can't understand why 2 objects are used.
LabelPlaceContext have DbSet<...> inside

2022-09-08 16:15 UTC, DzmitryBratchuk commented on LabelPlace.Dal/UnitOfWork/UnitOfWork.cs
> +        //private readonly GenericRepository<BaseEntity> _baseEntityRepository;
Remove useless comment

2022-09-08 16:15 UTC, DzmitryBratchuk commented on LabelPlace.Dal/UnitOfWork/UnitOfWork.cs
> +        private GenericRepository<User> _userRepository;
How are you going to use this UnitOfWork, if for example you need to implement a company search by name?
Your GenericRepository contains only couple of methods that common for specific repositories. You will not be able to call the _companyRepository.GetByName() because the GenericRepository does not have such a method.

Here you should use specific repositories objects (ICompanyRepository for example). And ICompanyRepository must be inherited from GenericRepository

2022-09-08 16:15 UTC, DzmitryBratchuk commented on LabelPlace.Dal/UnitOfWork/UnitOfWork.cs
> +        }
Can be simplified:
public ICompanyRepository Companies => _companyRepository ??= new CompanyRepository(_context);

2022-09-08 16:15 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Entities/Role.cs
> +        public RoleType? Type { get; set; }
Why nullable?

2022-09-08 16:15 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Entities/Project.cs
> +        public ProjectType? Type { get; set; }
This one from ProjectConfiguration
![image](https://user-images.githubusercontent.com/56396360/189171470-a2e5f72d-606a-4a72-90e7-8a1723403a0b.png)

Required configuration but Nullable fields?

2022-09-08 16:15 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Enums/ProjectStatus.cs
> +        Paused = 3
Better Suspended not Paused

2022-09-08 16:15 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Enums/RoleType.cs
> +        Adminsitrator = 1,
Spelling error
Administrator

2022-09-08 16:15 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Enums/RoleType.cs
> +        User = 2,
Bad name. Administrator, Validator and Customer are also users!
Maybe Annotator?

2022-09-13 13:31 UTC, MikutishviliDavid commented on LabelPlace.Dal/GenericRepository/GenericRepository.cs
> +            TEntity entityToDelete = _entities.Find(id);
OK, so far I've changed the implementation

2022-09-13 13:36 UTC, MikutishviliDavid commented on LabelPlace.Dal/GenericRepository/GenericRepository.cs
> +        public virtual void Delete(TEntity entityToDelete)
I've leaved this method and I've deleted the other one

2022-09-13 13:36 UTC, MikutishviliDavid commented on LabelPlace.Dal/GenericRepository/IGenericRepository.cs
> +    public interface IGenericRepository<TEntity> where TEntity : class
Done

2022-09-13 13:37 UTC, MikutishviliDavid commented on LabelPlace.Dal/LabelPlaceContext.cs
> +            modelBuilder.ApplyConfigurationsFromAssembly(typeof(CompanyConfiguration).Assembly);
Done

2022-09-13 13:38 UTC, MikutishviliDavid commented on LabelPlace.Dal/GenericRepository/GenericRepository.cs
> +        private readonly DbSet<TEntity> _entities;
I gonna use only LabelPlaceContext

2022-09-13 13:38 UTC, MikutishviliDavid commented on LabelPlace.Dal/UnitOfWork/UnitOfWork.cs
> +        //private readonly GenericRepository<BaseEntity> _baseEntityRepository;
Done

2022-09-13 13:41 UTC, MikutishviliDavid commented on LabelPlace.Dal/UnitOfWork/UnitOfWork.cs
> +        private GenericRepository<User> _userRepository;
I changed the implementation and will come back to this later when I create the necessary logic for it

2022-09-13 13:41 UTC, MikutishviliDavid commented on LabelPlace.Dal/UnitOfWork/UnitOfWork.cs
> +        }
I changed the implementation and will come back to this later when I create the necessary logic for it

2022-09-13 13:43 UTC, MikutishviliDavid commented on LabelPlace.Domain/Entities/Role.cs
> +        public RoleType? Type { get; set; }
I leaved it not nullable

2022-09-13 13:44 UTC, MikutishviliDavid commented on LabelPlace.Domain/Entities/Project.cs
> +        public ProjectType? Type { get; set; }
Ok, I hope I understand it)

2022-09-13 13:44 UTC, MikutishviliDavid commented on LabelPlace.Domain/Enums/ProjectStatus.cs
> +        Paused = 3
Done

2022-09-13 13:44 UTC, MikutishviliDavid commented on LabelPlace.Domain/Enums/RoleType.cs
> +        Adminsitrator = 1,
Done

2022-09-13 13:44 UTC, MikutishviliDavid commented on LabelPlace.Domain/Enums/RoleType.cs
> +        User = 2,
Done

2022-09-14 09:44 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Enums/RoleType.cs
> +        Adminsitrator = 1,
NO!!!
Was Admi**nsi**trator but need Admi**nis**trator!!

2022-09-14 09:45 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Enums/RoleType.cs
> +        User = 2,
NO!!!
User -> Annotator

2022-09-14 10:43 UTC, DzmitryBratchuk commented on LabelPlace.Dal/GenericRepository/GenericRepository.cs
> +    public class GenericRepository<TEntity> : IBaseRepository<TEntity>
Of course, if you change the interface name to IBaseRepository, change the class name to BaseRepository as well.

2022-09-14 10:43 UTC, DzmitryBratchuk commented on LabelPlace.Dal/UnitOfWork/UnitOfWork.cs
> +    public class UnitOfWork : IDisposable
Where is IUnitOfWork interface?

2022-09-14 10:43 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Entities/IntId.cs
> +    public class IntId : BaseEntity
IntId not the best name

2022-09-14 10:43 UTC, DzmitryBratchuk commented on LabelPlace.Domain/Entities/GuidId.cs
> +    public class GuidId : BaseEntity
GuidId not the best name

2022-09-14 11:48 UTC, MikutishviliDavid commented on LabelPlace.Domain/Enums/RoleType.cs
> +        Adminsitrator = 1,
Done

2022-09-14 11:50 UTC, MikutishviliDavid commented on LabelPlace.Domain/Enums/RoleType.cs
> +        User = 2,
Sorry, I didn't understand right away )

2022-09-14 11:52 UTC, MikutishviliDavid commented on LabelPlace.Dal/GenericRepository/GenericRepository.cs
> +    public class GenericRepository<TEntity> : IBaseRepository<TEntity>
Done

2022-09-14 12:17 UTC, MikutishviliDavid commented on LabelPlace.Dal/UnitOfWork/UnitOfWork.cs
> +    public class UnitOfWork : IDisposable
Added it

2022-09-14 12:19 UTC, MikutishviliDavid commented on LabelPlace.Domain/Entities/IntId.cs
> +    public class IntId : BaseEntity
Renamed

2022-09-14 12:19 UTC, MikutishviliDavid commented on LabelPlace.Domain/Entities/GuidId.cs
> +    public class GuidId : BaseEntity
Renamed

2022-09-14 12:40 UTC, DzmitryBratchuk approved these changes

2022-09-14 12:40 UTC, merged